### ISSUE TITLE
Crash on startup Eclipse Version: Kepler (20140224-0627)

### ISSUE THREAD

**Issue by lapauwThomas** [anb0s/eclox#180] opened 2017-02-06 11:41 UTC
After installing Eclox eclipse fails to start up each time. Tested with both version 0.10 and 0.8. For the log file see attachment. Startup with -clean argument does not solve the problem. 

Eclipse version:
Version: Kepler Service Release 2
Build id: 20140224-0627
(bundled with intel/altera Quartus Nios Build tools)

[1486380773632.log.txt](https://github.com/anb0s/eclox/files/754469/1486380773632.log.txt)

**Comment by anb0s** [comment] 2017-02-06 11:51
Thanks, I've looked at your log and cannot find any eclox classes involved. With this information i cannot investigate more and have no idea how it is related to installation of eclox.

The error i see is:
...
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.widgets.Display cannot be found by org.eclipse.e4.ui.css.swt.theme_0.9.100.v20130515-1857
...

May be something else was installed together with eclox? Some other platform plugins etc.? Please try to install eclox alone -> disable all other update site and update resolution features in update manager. To be sure only eclox is installed and no other plugins are updated etc....

**Comment by lapauwThomas** [comment] 2017-02-06 12:23
Thanks for the quick response.

There is only one other package installed:   
Nios II Embedded Design Suite	16.1.0.v20161025-0323	com.altera.sbt4e.product

Without Eclox it works as it should, but after installing eclox using the update site, it asks for restart and then it fails to start and it generates the previously attached log file. The only solution is to delete the eclox files from the plugins directory.

So it is entirely possible that it is a compatibility issue.


Is there a way to manually install Eclox on windows?

**Comment by anb0s** [comment] 2017-02-12 19:02
Hello i've now tested with Eclipse 4.3.2 (Kepler) - doxygen editor and also build is working:

![image](https://cloud.githubusercontent.com/assets/95811/22865064/babad66e-f15c-11e6-813b-5c45d0410609.png)

I've still no idea what is wrong here...

**Manual instal**: see http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fp2_dropins_format.html

create the folder structure under your eclipse directory (here eclipse):
```
eclipse/
    dropins/
      eclox/
       eclipse/
         features/
         plugins/ 

```
and copy the jar files files from here: https://github.com/anb0s/eclox/tree/master/eclox.site/updates/testing/0.11/0.11.0.v20170121-2217
to local features and plugins subfolders under eclox/eclipse.

**Comment by anb0s** [comment] 2017-02-13 16:11
Please try to start eclipse with "-debug" option and look if the output shows something about class loader errors or eclox etc.

**Comment by anb0s** [comment] 2017-02-22 10:03
I want to release 0.11 soon. Do you have any news for me about this issue? Thanks!

**Comment by lapauwThomas** [comment] 2017-02-23 09:31
Hi,

I tried the manual install, but eclipse does not detect the plugin. But I noticed that the install directory using the installer from inside eclipse puts the files into a hidden directory in the user folder. C:\Users\thoma\.altera.sbt4e\16.1.0.196-windows64\plugins

I tried to install it again the way it used to fail, but now it installed perfectly even though I had tried to install it multiple times before. Are you still interested in a debug log?

Best Regards
Thomas

**Comment by anb0s** [comment] 2017-02-23 09:40
Thank You for the update!

If you have some logs that shows the problem i will investigate more or just append it to the issue to have it described for later similar requests.

P.S.: You can try the new build from #181 if nothing breaking is there i will release eclox 0.11 until 27.02.17

**Comment by anb0s** [comment] 2017-02-26 07:14
v0.11 released, close this because not reproducable here, please add more info if possible or reopen if you have error logs showing the problem. Thanks.

**Closed as completed by anb0s** 2017-02-26 07:14 UTC
Labels: help wanted, wontfix, Eclipse platform bug or not compatible, Other plugin bug or not compatible

**Comment by mohankotgire** [comment] 2017-03-31 04:10
Hi,

I  am facing similar issue.
I am using the latest  version of Eclox u.0.11 ( I tried all the procedures mentioned above, used the latest version\also tried by downloading from Eclipse market \ used the latest testing fliles from git) 
When i tried to open eclipse after installing\trying above procedures , it failed to restart the eclipse throwing the exception rooting to the file attached .

Please help me resolving this . 

Eclipse version used :  Kepler Service Release 

[1490932781724.txt](https://github.com/anb0s/eclox/files/884495/1490932781724.txt)

Thanks in advance!
Regards,
Mohan

**Comment by anb0s** [comment] 2017-03-31 10:38
Hi,

i've looked in your logs and cannot find any eclox related entries -> only crashes from the platform.
I've also tried again eclox with my Kepler installations and do not see any problems. My main Eclipse is Neon...

Sorry, but i've still no idea what goes wrong and do not know how to investigate more...

Regards,
Andre
